### ISSUE TITLE
doesn't work on my (unusual) setup

### ISSUE THREAD

**Issue by mark-hahn** [russlescai/atom-touch-events#10]
I am running atom in ubuntu 14.04 inside an X-window in a chromebook (using crouton).  I'm on a chromebook pixel which has a touch screen.  I finally had time to try this and I'm disappointed to say that none of the events seem to be getting through. 

It is possible that no touch events are supported in Crouton.  I will ask on the Crouton forum about this.  If they say the events should be getting to the X-window then I'll try to chase the problem down.

Has anyone reported using this in a linux environment?  I seem to remember you are on a windows tablet.

**Comment by russlescai** [comment]
@mark-Hahn yep I'm using a surface pro 2.

If it helps, I'm using the native touchstart and touchmove events.

The VM layer may be translating touch events to click events. Not sure though.

Let me know if there is a way I can help you track it down.

**Comment by mark-hahn** [comment]
Check out https://github.com/dnschneid/crouton/issues/1757

**Comment by russlescai** [comment]
@mark-Hahn also worth checking how chrome responds to touch events on Ubuntu with crouton.

**Comment by mark-hahn** [comment]
I've never tried chrome in crouton since it's already outside of crouton.
Unfortunately it doesn't seem to work in crouton.
https://github.com/dnschneid/crouton/issues/1761

**Comment by nylki** [comment]
I am using Fedora 21 with Gnome 3.14. The scroll and zoom gestures don't work in a text editor. Is there any way I can contribute to find the issue?

**Comment by russlescai** [comment]
@nylki Yeah absolutely. Firstly, test if Chromium responds to touch events as well. This package uses the native Chromium touch events to detect gestures.

Are you running Fedora on a VM or similar? Do other apps respond to touch events?

Depending on how technical you would like to get, you could do the following to check if *any* touch events are being fired by atom (Chromium):

1. Open Dev Tools
2. On the right panel, expand "Event Listener Breakpoints"
3. Select the "Touch" item

swipe around on the atom screen (outside of dev tools), and see if the debugger kicks in.

**Comment by nylki** [comment]
@russlescai 
> Firstly, test if Chromium responds to touch events as well."

 I haven't got Chromium installed on my machine, and it's not going to happen. However I'll help on the other points.

Atom responds to touch events when tapping on text:
![bildschirmfoto von 2015-05-26 23 30 24](https://cloud.githubusercontent.com/assets/1710598/7823910/3bde6e6a-03ff-11e5-8bee-67ee2beb4e05.png)


> Are you running Fedora on a VM or similar?

no. It's running straight on my Thinkpad Yoga.

> Do other apps respond to touch events?

Yes. Pinch-to-Zoom works fine in Evince for example.


> Select the "Touch" item

There is no `Touch` item, but `touchmove`, `touchstart` and `touchend`

> swipe around on the atom screen (outside of dev tools), and see if the debugger kicks in.

Nothing changes, as far as I can tell. But none of the listed event-listeners seem to change (are they supposed to?), even when clicking.

**Comment by russlescai** [comment]
It's been a while since this issue was last discussed. This package can only respond to events raised by Atom, which in some cases may not occur due to specific hardware configurations.
