### ISSUE TITLE
Feature request: Service providers for the events

### ISSUE THREAD

**Issue by olmokramer** [russlescai/atom-touch-events#8]
It would be seriously awesome if this package would provide these events as a service to other packages! I would love to implement a swipe event into my [autohide-tree-view](https://atom.io/packages/autohide-tree-view) package :) (And I would like to not have to repeat what you've already done :wink:).

Do you think this is feasible? Or am I missing the point of this package? I can't try it out, as I don't have a touch enabled monitor :(

**Comment by russlescai** [comment]
@olmokramer I was actually experimenting with swiping to hide the treeview yesterday. :)

I looked at your package, and it wasn't apparent how to trigger hide the treeview.

Happy to provide them as a service, however I will need to determine the best way to do that (haven't done it before in an atom package).

I have deliberately separated the event subscriptions in atom-touch-events.coffee from behaviour, such as scrolling/zooming, for this exact reason.

I'll take a read through https://atom.io/docs/v0.198.0/behind-atom-interacting-with-packages-via-services and see how I can best expose them.

**Comment by russlescai** [comment]
@olmokramer I have created a PR #9 to expose the event services to other packages using the atom API.

Let me know what you think or if you have any issues.

**Comment by olmokramer** [comment]
Awesome! And very quickly indeed! :) I'll take a look in the afternoon, but from what I can see, it looks fairly simple and sufficient. Thanks!

**Comment by russlescai** [comment]
awesome. :) I've merged the PR, let me know if you would like me to test anything.

**Comment by olmokramer** [comment]
Hey man, I'm trying to get this to work, but I'm getting an error about `Cannot read property 'on' of undefined` in [`lib/touch-events.coffee` line 40](https://github.com/russlescai/atom-touch-events/blob/master/lib/atom-touch-events.coffee#L40), even though [I'm waiting for `atom-touch-events` to be activated](https://github.com/olmokramer/atom-autohide-tree-view/blob/touch-events/lib/autohide-tree-view.js#L33). And [L35](https://github.com/olmokramer/atom-autohide-tree-view/blob/touch-events/lib/autohide-tree-view.js#L35) logs indeed that `atom-touch-events` is activated. Any ideas what could be happening?

You can find the changes on the [`touch-events`](https://github.com/olmokramer/atom-autohide-tree-view/tree/touch-events) branch of the autohide-tree-view repository.

**Comment by russlescai** [comment]
hey mate, I'll take a look tonight and see what I find.

**Comment by russlescai** [comment]
Hey @olmokramer I think I've fixed the issue.

I needed to reference the Emitter on the AtomTouchEvent module, instead of calling this.emitter, since 'this' is now the consumer.

I tested it using a test sample package on my local machine, and included the code I used to test on the readme.

It's published so all you should need to do now is update the version of the atom touch events package.

Let me know how you go. :)

**Comment by olmokramer** [comment]
Hey man, Thanks! Makes sense it didn't work.

It seems to be working on my side, I'll let you know when there's something to test :)

**Comment by olmokramer** [comment]
Hey @russlescai, chrome actually has the ability to emulate touch events, so I figured it all out by myself! It would be nice, though, if you could test it on a real touch screen :)

I submitted a PR that adds another callback that will be triggerd on the `touchend` event. I needed this for autohide-tree-view.

**Comment by russlescai** [comment]
Hey @olmokramer I have published the merged PR with your changes. Thanks for that. :+1: 

I tried testing your branch, but was getting other issues (probably the branch->apm install process not working correctly).

If you want to publish the changes in autohide and I can check if they work with my touch device?

**Comment by olmokramer** [comment]
Oops, I had touch events disabled by default settings, you could enable them in the package settings. Pushed a new version that enables them by default.

The partial keyframes error is weird though, as I'm explicitly setting a start frame and an end frame. I'll look into it. Thanks for testing!

**Comment by russlescai** [comment]
I patched a new version of atom touch events package, I found a few issues relating to slightly different arg parameters for touchEnd events.

Should be good to go now. :)

**Comment by russlescai** [comment]
I retested this morning, I'm not getting the animation errors any more.

One thing I noted was that it is difficult to swipe in to open the treeview (since it checks if the source is the treeview, which is a small segment).

What I was thinking you could do is use a margin value to detect a swipe right from the left side of the screen (if treeview is on the left) to open it.

Something like:

```
function swipeRightStart({args, source, deltaX})
{
  if (!getConfig("showOn").match("touch")) return;
  
  if (args.changedTouches[0].pageX < 300) { // arbitary 300 pixel left margin to detect swipe)
    show(0);
  }
  else if (screenX - args.changedTouches[0].pageX < 300) { // arbitary 300 pixel right margin to detect swipe - todo: determine screenX
   hide(0);
  }
}
```

What do you think?

**Comment by olmokramer** [comment]
Yeah, that might be a good idea :) Thanks! I'll try to get to it this weekend.

**Comment by olmokramer** [comment]
Hey man, I just updated and pushed to the touch-events branch. It now checks if the user swipes from a configurable area (default is 50px wide). It requires the PR I submitted, that fixes the `touchend` events.

**Comment by russlescai** [comment]
cheers mate :)  I'll give it a test and merge.

**Comment by russlescai** [comment]
cheers mate :)  I'll give it a test and merge.

**Comment by russlescai** [comment]
I've published the new version (version 19), so I think you're good to go. :)

**Comment by russlescai** [comment]
@olmokramer I tested your touch-events branch and it works well for me. :+1:

**Comment by olmokramer** [comment]
That's awesome! Thanks mate, for the help and testing!! And for atom-touch-events :)

There's a couple of bugs I still need to fix, and I'd like to implement [issues/21](https://github.com/olmokramer/autohide-tree-view/issues/21).

Anyway, closing this one :) Thanks again!
